### ISSUE TITLE
How do we deploy the jar file that gets generated on ubuntu ? 

### ISSUE THREAD

**Issue by nelaturuk** [clydedacruz/obligation-webapp-springboot#1]
Hi, 

I am trying to setup the sprint webserver with this project for corda backend. I am new to spring boot. The jar file gets generated but when i try starting the jar file. Its gives me below error: 

no main manifest attribute, in obligation-webapp-springboot.jar

Can you let me know if you have a process for deploying jar as well. Thank you.

**Comment by clydedacruz** [comment]
@nelaturuk 

I’ve just added a new commit to the repository . You should now be able to run the jar without problems.
Feel free to reach out for any other questions!

**Comment by nelaturuk** [comment]
thank you for the immediate fix.
